apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: {{ .Values.whoami.replicas }}
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: {{ .Values.whoami.image }}
          ports:
            - containerPort: {{ .Values.whoami.service.port }}