apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  selector:
    app: whoami
  ports:
    - name: http
      port: {{ .Values.whoami.service.port }}
      targetPort: {{ .Values.whoami.service.port }}